// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFL.Models;

namespace NFL.Migrations
{
    [DbContext(typeof(TeamContext))]
    [Migration("20211210162529_Initial3")]
    partial class Initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NFL.Models.Conference", b =>
                {
                    b.Property<string>("ConferenceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConferenceId");

                    b.ToTable("Conference");

                    b.HasData(
                        new
                        {
                            ConferenceId = "afc",
                            Name = "AFC"
                        },
                        new
                        {
                            ConferenceId = "nfc",
                            Name = "NFC"
                        });
                });

            modelBuilder.Entity("NFL.Models.Division", b =>
                {
                    b.Property<string>("DivisionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DivisionId");

                    b.ToTable("Division");

                    b.HasData(
                        new
                        {
                            DivisionId = "north",
                            Name = "North"
                        },
                        new
                        {
                            DivisionId = "south",
                            Name = "South"
                        },
                        new
                        {
                            DivisionId = "east",
                            Name = "East"
                        },
                        new
                        {
                            DivisionId = "west",
                            Name = "West"
                        });
                });

            modelBuilder.Entity("NFL.Models.Team", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConferenceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DivisionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LogoImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("DivisionId");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            TeamId = "ari",
                            ConferenceId = "nfc",
                            DivisionId = "west",
                            LogoImage = "ARI.png",
                            Name = "Arizona Cardinals"
                        },
                        new
                        {
                            TeamId = "atl",
                            ConferenceId = "nfc",
                            DivisionId = "south",
                            LogoImage = "ATL.png",
                            Name = "Atlanta Falcons"
                        },
                        new
                        {
                            TeamId = "bal",
                            ConferenceId = "afc",
                            DivisionId = "north",
                            LogoImage = "BAL.png",
                            Name = "Baltimore Ravens"
                        },
                        new
                        {
                            TeamId = "buf",
                            ConferenceId = "afc",
                            DivisionId = "east",
                            LogoImage = "BUF.png",
                            Name = "Buffalo Bills"
                        },
                        new
                        {
                            TeamId = "car",
                            ConferenceId = "nfc",
                            DivisionId = "south",
                            LogoImage = "CAR.png",
                            Name = "Carolina Panthers"
                        },
                        new
                        {
                            TeamId = "chi",
                            ConferenceId = "nfc",
                            DivisionId = "north",
                            LogoImage = "CHI.png",
                            Name = "Chicago Bears"
                        },
                        new
                        {
                            TeamId = "cin",
                            ConferenceId = "afc",
                            DivisionId = "north",
                            LogoImage = "CIN.png",
                            Name = "Cincinnati Bengals"
                        },
                        new
                        {
                            TeamId = "cle",
                            ConferenceId = "afc",
                            DivisionId = "north",
                            LogoImage = "CLE.png",
                            Name = "Cleveland Browns"
                        },
                        new
                        {
                            TeamId = "dal",
                            ConferenceId = "nfc",
                            DivisionId = "east",
                            LogoImage = "DAL.png",
                            Name = "Dallas Cowboys"
                        },
                        new
                        {
                            TeamId = "den",
                            ConferenceId = "afc",
                            DivisionId = "west",
                            LogoImage = "DEN.png",
                            Name = "Denver Broncos"
                        },
                        new
                        {
                            TeamId = "det",
                            ConferenceId = "nfc",
                            DivisionId = "north",
                            LogoImage = "DET.png",
                            Name = "Detroit Lions"
                        },
                        new
                        {
                            TeamId = "gb",
                            ConferenceId = "nfc",
                            DivisionId = "north",
                            LogoImage = "GB.png",
                            Name = "Green Bay Packers"
                        },
                        new
                        {
                            TeamId = "hou",
                            ConferenceId = "afc",
                            DivisionId = "south",
                            LogoImage = "HOU.png",
                            Name = "Houston Texans"
                        },
                        new
                        {
                            TeamId = "ind",
                            ConferenceId = "afc",
                            DivisionId = "south",
                            LogoImage = "IND.png",
                            Name = "Indianapolis Colts"
                        },
                        new
                        {
                            TeamId = "jax",
                            ConferenceId = "afc",
                            DivisionId = "south",
                            LogoImage = "JAX.png",
                            Name = "Jacksonville Jaguars"
                        },
                        new
                        {
                            TeamId = "kc",
                            ConferenceId = "afc",
                            DivisionId = "west",
                            LogoImage = "KC.png",
                            Name = "Kansas City Chiefs"
                        },
                        new
                        {
                            TeamId = "lac",
                            ConferenceId = "afc",
                            DivisionId = "west",
                            LogoImage = "LAC.png",
                            Name = "Los Angeles Chargers"
                        },
                        new
                        {
                            TeamId = "lar",
                            ConferenceId = "nfc",
                            DivisionId = "west",
                            LogoImage = "LAR.png",
                            Name = "Los Angeles Rams"
                        },
                        new
                        {
                            TeamId = "mia",
                            ConferenceId = "afc",
                            DivisionId = "east",
                            LogoImage = "MIA.png",
                            Name = "Miami Dolphins"
                        },
                        new
                        {
                            TeamId = "min",
                            ConferenceId = "nfc",
                            DivisionId = "north",
                            LogoImage = "MIN.png",
                            Name = "Minnesota Vikings"
                        },
                        new
                        {
                            TeamId = "ne",
                            ConferenceId = "afc",
                            DivisionId = "east",
                            LogoImage = "NE.png",
                            Name = "New England Patriots"
                        },
                        new
                        {
                            TeamId = "no",
                            ConferenceId = "nfc",
                            DivisionId = "south",
                            LogoImage = "NO.png",
                            Name = "New Orleans Saints"
                        },
                        new
                        {
                            TeamId = "nyg",
                            ConferenceId = "nfc",
                            DivisionId = "east",
                            LogoImage = "NYG.png",
                            Name = "New York Giants"
                        },
                        new
                        {
                            TeamId = "nyj",
                            ConferenceId = "afc",
                            DivisionId = "east",
                            LogoImage = "NYJ.png",
                            Name = "New York Jets"
                        },
                        new
                        {
                            TeamId = "oak",
                            ConferenceId = "afc",
                            DivisionId = "west",
                            LogoImage = "OAK.png",
                            Name = "Oakland RaIders"
                        },
                        new
                        {
                            TeamId = "phi",
                            ConferenceId = "nfc",
                            DivisionId = "east",
                            LogoImage = "PHI.png",
                            Name = "Philadelphia Eagles"
                        },
                        new
                        {
                            TeamId = "pit",
                            ConferenceId = "afc",
                            DivisionId = "north",
                            LogoImage = "PIT.png",
                            Name = "Pittsburgh Steelers"
                        },
                        new
                        {
                            TeamId = "sea",
                            ConferenceId = "nfc",
                            DivisionId = "west",
                            LogoImage = "SEA.png",
                            Name = "Seattle Seahawks"
                        },
                        new
                        {
                            TeamId = "sf",
                            ConferenceId = "nfc",
                            DivisionId = "west",
                            LogoImage = "SF.png",
                            Name = "San Francisco 49ers"
                        },
                        new
                        {
                            TeamId = "tb",
                            ConferenceId = "nfc",
                            DivisionId = "south",
                            LogoImage = "TB.png",
                            Name = "Tampa Bay Buccaneers"
                        },
                        new
                        {
                            TeamId = "ten",
                            ConferenceId = "afc",
                            DivisionId = "south",
                            LogoImage = "TEN.png",
                            Name = "Tennessee Titans"
                        },
                        new
                        {
                            TeamId = "was",
                            ConferenceId = "nfc",
                            DivisionId = "east",
                            LogoImage = "WAS.png",
                            Name = "Washington Redskins"
                        });
                });

            modelBuilder.Entity("NFL.Models.Team", b =>
                {
                    b.HasOne("NFL.Models.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId");

                    b.HasOne("NFL.Models.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId");
                });
#pragma warning restore 612, 618
        }
    }
}
